const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
/**
 * Webpack starts packing in './src/js/index/js'
 * The main style sheet file, './src/scss/site.scss', is imported in './src/js/index/js' 
 * 
 * Three files are generated by Webpack in the './dist' directory:
 *  - main.js
 *  - style.css
 *  - index.html
 */
module.exports = {
  entry: { main: './src/js/index.js' },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js'
  },
  module: {
    rules: [
      /**
       * css-hot-loader is used to hot reload scss with webpack dev server
       * MiniCssExtractPlugin is used to extract a separate css file
       */
      {
        test: /\.scss$/,
        use: [
          'css-hot-loader',
          MiniCssExtractPlugin.loader,
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader'
        ]
      }
    ]
  },
  /**
   * Whatching all files in './src' will hot reload changes in index.html, too
   */
  devServer: {
    contentBase: './src',
    watchContentBase: true
  },
  plugins: [ 
    new HtmlWebpackPlugin({
        inject: true,
        hash: true,
        template: './src/index.html',
        filename: 'index.html'
    }),
    new MiniCssExtractPlugin({
      filename: "style.css"
    })
  ]
};