const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

/**
 * Webpack starts packing in './src/js/index/js'
 * The main style sheet file, './src/scss/site.scss', is imported in './src/js/index/js' 
 * 
 * Three files are generated by Webpack in the './dist' directory:
 *  - main.js
 *  - style.css
 *  - index.html
 */
module.exports = {
  entry: { main: './src/js/index.js' },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js'
  },
  module: {
    rules: [
      /**
       * css-hot-loader is used to hot reload scss with webpack dev server
       * ExtractTextPlugin is used to extract a separate css file
       */
        {
            test: /\.scss$/,
            use: ['css-hot-loader'].concat(ExtractTextPlugin.extract(
              {
                fallback: 'style-loader',
                use: ['css-loader', 'sass-loader']
              }))
          }
    ]
  },
  /**
   * Whatching all files in './src' will hot reload changes in index.html, too
   */
  devServer: {
    contentBase: './src',
    watchContentBase: true
  },
  plugins: [ 
    new ExtractTextPlugin({filename: 'style.css'}),
    new HtmlWebpackPlugin({
        inject: true,
        hash: true,
        template: './src/index.html',
        filename: 'index.html'
    })
  ]
};